username: ENC[AES256_GCM,data:6ouACKlLEbaXZD3lSypPog==,iv:lIKfxI2dezcVIk3n9Nqic3pYSEZBvC9bN4JGHdMZZW8=,tag:uRY5PTCvA0K1kuM+K0qQGQ==,type:str]
password: ENC[AES256_GCM,data:GDsulefsQvwF7748+TtGyQ==,iv:HTnDqhzcZPJ515yUBaRmF4cXGUQ7h/vD6F/mk3PbVZ8=,tag:2wKivDlddqHS/UUIyQpqCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-27T08:16:26Z"
    mac: ENC[AES256_GCM,data:s5EQo+ikBgINmsuR5sHnrlMOOlMOKVl2zL4SgUnuelNuQhXxDADvrtq2Y6Q4XmosRNn7pbn7U4sqhc2Zb9R8cCDUYK3jn66qwMYk6QkZ7dvXwRGIk3NF960UbHiyMCDpcyzkffqVUVL1RwVJz5N3Z9S8YBZrRHvmKgboWxtpTX4=,iv:3vfms7GOU559BctUQaP4/AUOrDs8hmk79OsCRbFoVMs=,tag:PTRSe5J7fTvX99sCBstnZw==,type:str]
    pgp:
        - created_at: "2021-09-26T21:10:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAz2aceqw41YlAQv/S0gPCYh3fbo4v5KTsqMAjU/wrwFjcylRL60tCQHEF0Rz
            h+tw1/PK/zr0upAxO+LoSPV4u11Ya/U1EMXYQy6WEDL/ju9rAS1+ydpL2EefLn/o
            LKE25kEKAKqOv1oj1WLSrC1I5OuNNCfqLZ1Yv9EDf23X6EKNa2ZxnmnK0bdodBOy
            CyTMsC9VXTjSNMHjmxWn/R5XZsQTux12KClAP6WposlweZwJtXAk3JVg+P6Oysv5
            ejdvZ7aQvUBaeAfwghcJBsfMk+YFj8Os5ol6QUE5Vr5QEzHSn9yf6aJZZqd8LOyC
            OcSzQT649wY2gVAU+4Iv4QFI6gmkVdvPZEbTejFkF1K9nuH5Ib0nEwpLuB1hW0wp
            MaoobqfXC9OfdDegK8L855nGCuYIyoBvunHb5UXDLLcrVPhEn1G5W5+SgeEL5fCN
            NUX5Gq4IHmcTharKl09xaJwn6uohPta+dpCiWzp3IVK0Zcq/cksSzqGzL9YqH4LV
            EAOe8Z+xWmEcWTvB3e400l4BVpGVptfvbaqcLO/DMe6Eby2OCphPCFJkz1/Mu8EH
            iaBjzDZe34j2cx1V0cqw9Y8pedPKXXhS/GlYmkgWelr7UCwSrgfnVXMzcPGAAD/H
            mSBwfacfRrzMgFCtyqVb
            =Hnlx
            -----END PGP MESSAGE-----
          fp: 66085DB944C3F56636502386B490FCFB5AF7A518
    unencrypted_suffix: _unencrypted
    version: 3.7.1
