version: '3.7'

networks:
  monitoring.networks:

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "5"
    tag: "{{.ImageName}}|{{.Name}}"

x-defaults:
  &defaults
  logging: *default-logging
  restart: unless-stopped
  networks:
    - monitoring.networks

services:

  app_python:
    image: safinsaf/devops_app_python:${TAG:-latest}
    container_name: app_python
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    <<: *defaults

  app_java:
    image: safinsaf/devops_app_java:${TAG:-latest}
    container_name: app_java
    ports:
      - "8081:8081"
    expose:
      - 8081
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    <<: *defaults

  grafana:
    build:
      context: ${PWD}/grafana
      args:
        - NGINX_GRAFANA_HOST=${NGINX_GRAFANA_HOST}
        - GRAFANA_VERSION=${GRAFANA_VERSION}
    container_name: monitoring.grafana
    volumes:
      - ${PWD}/grafana/grafana-data:/var/lib/grafana
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=monitoring.grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000
    expose:
      - 3000
    ports:
      - "3000:3000"
    labels:
      org.label-schema.group: "monitoring"
    <<: *defaults


  promtail:
    image: grafana/promtail:${LOKI_VERSION}
    container_name: monitoring.promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/promtail/promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail/promtail.yml:/etc/promtail/promtail.yml
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    labels:
      org.label-schema.group: "monitoring"
    <<: *defaults

  loki:
    container_name: monitoring.loki
    image: grafana/loki:${LOKI_VERSION}
    expose:
      - 3100
    ports:
      - "3100:3100"
    volumes:
      - ${PWD}/loki/loki-config.yml:/etc/loki-config.yml
      - ${PWD}/loki/loki-data:/tmp/loki/
    command: -config.file=/etc/loki-config.yml
    labels:
      org.label-schema.group: "monitoring"
    <<: *defaults