---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_install_packages }}"

- name: Install docker libraries
  pip:
    name:
      - docker== 5.0.2
      - docker-compose==1.29.2
    state: present

- name: Create directory for app
  file:
    path: /app_python/
    state: directory

- name: Copy docker-compose
  copy:
    src: docker-compose.yml
    dest: /app_python/docker-compose.yml

- name: deploy Docker Compose stack
  docker_compose:
    project_src: /app_python
    files:
      - docker-compose.yml